### ISSUE TITLE
FormatValidator fails on undefined value

### ISSUE THREAD

**Issue by yossi-shasho** [lcoq/ember-validations#12]
When `FormatValidator`  is the only validation attached to a property, when validating without a property value, an exception is thrown.

**Comment by lcoq** [comment]
I just fixed this bug (see 78e8cb4).

A property value that does not respond to `match` function is replaced by an empty string. Consequently, the matching is made even for a falsy value.
if you don't want this behavior, you can set the `allowBlank` option to `true`.

Let me know if you have any trouble or suggestion with this behavior.
