### ISSUE TITLE
Custom validation function never returns true in model.validate()

### ISSUE THREAD

**Issue by nodesocket** [lcoq/ember-validations#23]
Trying to use a custom validate function:

```
validations: {
  password: {
    presence: true,
    length: {
      minimum: 6
    },
    format: {
      validator: function (object, attribute, value) {
        if (!Balanced.Utils.isValidPassword(value)) {
          object.set('hasError', true);
          return false;
        }
      }
    }
 }
```

  }

But this is returning `false` every-time I call `model.validate()` even though I confirm that `Balanced.Utils.isValidPassword()` is returning `true`. What is the right way to do this?

**Comment by lcoq** [comment]
Why did you close the issue ? Was it a bug in your code, or is this issue still present ?
FYI, you do not have to specify a return value in the validator function, you just have to add an error in the `validationErrors` property. 
The code in the [readme](https://github.com/lcoq/ember-validations#on-the-fly) should works
