### ISSUE TITLE
I can not customize my validation error messages

### ISSUE THREAD

**Issue by zhangyuhui** [lcoq/ember-validations#32]
How can I define my own error messages?

**Comment by lcoq** [comment]
It depends on which kind of error message you wants to customize.

If you want to change all the error messages for `blank` errors, you can do: 

```
Ember.ValidationError.addMessage('blank', "my custom error message");
```

If you want to define a custom error message for a specific property, there is sadly no way to do that yet.

I close this issue as this is a duplicate of #13 .
