### ISSUE TITLE
Allow automatic validation

### ISSUE THREAD

**Issue by lcoq** [lcoq/ember-validations#7]
It could be a good feature to have an option which make the validation automatically by listening each property that needs to be validated

**Comment by ghost** [comment]
Would be cool but only onblur.

**Comment by lcoq** [comment]
As this library is only related to models, not views, we let the user choose how handle validation in the views.
Basically, it will be an handlebar helper, or by subclassing a view (e.g. `Ember.TextField`), and re-call `validate` when desired.

Anyway, I will be glad to see how users are using them.
